spring:
  application:
    name: apiRouterZuulGate
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.18.0.147:3306/ag_datashare?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
  redis:
     host: 127.0.0.1
     port: 6379
     timeout: 1000
    # Redis数据库索引（默认为0）
     database: 2
  data:
     mongodb:
     uri: mongodb://ztgeo:123456@localhost:27017/http_db
server:
  port: 8001
zuul:
  ignored-patterns: /ztgeoNotice/**,/route/**
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
    max-total-connections: 1000
    max-per-route-connections: 50
customAttributes:
  # 存储用户发送数据的数据库名
  #接口转发的数据库名
  dbName: "httpGenera_db"
  #通知的数据库名
  dbSafeName: "httpSafe_db"