spring:
  application:
    name: apiRouterZuulGate
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.18.0.147:3306/ag_datashare?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
server:
  port: 8001
zuul:
  ignored-patterns: /ztgeoNotice/**,/route/**
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
    max-total-connections: 1000
    max-per-route-connections: 50
